import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, Code2, Contact, Mail, Menu, MessageCircle, X } from 'lucide-react'
import { projects } from './data/projects'
import { cases, labs, repositories, stack } from './data/content'
import { translate, type Language } from './data/translations'
import { SectionHeading } from './components/SectionHeading'
import { Hero } from './sections/Hero'

const nav = [['about','ABOUT'], ['experience','EXPERIENCE'], ['projects','PROJECTS'], ['lab','ENGINEERING LAB'], ['stack','STACK'], ['contact','CONTACT']]

function App() {
  const [menu, setMenu] = useState(false)
  const [active, setActive] = useState('home')
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('portfolio-language') as Language) || 'en')
  const t = (value: string) => translate(value, language)
  const changeLanguage = (next: Language) => { setLanguage(next); localStorage.setItem('portfolio-language', next); document.documentElement.lang = next }
  useEffect(() => {
    document.documentElement.lang = language
    const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { setActive(e.target.id); e.target.classList.add('visible') } }), { rootMargin: '-35% 0px -55%', threshold: 0 })
    document.querySelectorAll('section[id], .reveal').forEach(el => observer.observe(el))
    return () => observer.disconnect()
  }, [language])
  return <>
    <header><a href="#home" className="logo" aria-label="Home">JD<span>_</span></a><nav className={menu ? 'open' : ''}>{nav.map(([id, label]) => <a className={active === id ? 'active' : ''} href={`#${id}`} onClick={() => setMenu(false)} key={id}>{t(label)}</a>)}</nav><div className="header-tools"><div className="lang" aria-label="Language selector"><button className={language === 'en' ? 'selected' : ''} onClick={() => changeLanguage('en')}>EN</button><span>/</span><button className={language === 'es' ? 'selected' : ''} onClick={() => changeLanguage('es')}>ES</button></div><button className="menu" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <X /> : <Menu />}</button></div></header>
    <main>
      <Hero t={t} />
      <section id="about" className="section about"><SectionHeading t={t} index="01" eyebrow="ABOUT / PROFILE" title="FROM IDEA TO PRODUCTION." /><div className="about-layout reveal"><p className="about-lead">{t('I build complete web products across frontend, backend, data and delivery—with quality engineered into every layer.')}</p><div className="about-copy"><p>{t('My experience spans custom React platforms, Node.js services, APIs, databases, ecommerce and CMS projects. A strong QA background helps me deliver software that is not only functional, but reliable and accessible.')}</p><div className="metrics"><div><b>04</b><span>{t('Product layers')}</span></div><div><b>02</b><span>{t('Engineering perspectives')}</span></div><div><b>∞</b><span>{t('Curiosity to improve')}</span></div></div></div></div></section>
      <section id="experience" className="section"><SectionHeading t={t} index="02" eyebrow="CAREER.LOG" title="EXPERIENCE" copy="A multidisciplinary path across full stack development, digital platforms and software quality." /><div className="timeline reveal"><article><div className="timeline-marker">01</div><div className="timeline-time">{t('CORE EXPERIENCE')} <span>{t('PRODUCT ENGINEERING')}</span></div><div><h3>{t('Full Stack Development')}</h3><p>{t('Building complete production platforms from responsive interfaces to APIs, data models, integrations and deployment workflows.')}</p><div className="tags">{['React','TypeScript','Node.js','NestJS','Laravel','REST APIs','PostgreSQL','Docker'].map(x=><span key={x}>{x}</span>)}</div></div></article><article><div className="timeline-marker">02</div><div className="timeline-time">{t('PLATFORM EXPERIENCE')} <span>CMS / COMMERCE</span></div><div><h3>{t('Web & CMS Development')}</h3><p>{t('Creating content, institutional and ecommerce experiences for real organizations and audiences.')}</p><div className="tags">{['WordPress','Joomla','Shopify','JavaScript','Ecommerce','Responsive UI'].map(x=><span key={x}>{x}</span>)}</div></div></article><article><div className="timeline-marker">03</div><div className="timeline-time">2026 — {t('PRESENT')} <span>{t('QUALITY ENGINEERING')}</span></div><div><h3>{t('QA & Automation')}</h3><p>{t('Applying manual testing, browser automation, API validation and accessibility to make every release more reliable.')}</p><div className="tags">{['Playwright','Manual Testing','API Testing','Accessibility','Regression','CI/CD'].map(x=><span key={x}>{t(x)}</span>)}</div></div></article></div></section>
      <section id="projects" className="section projects-section"><SectionHeading t={t} index="03" eyebrow="SELECTED WORK" title="FEATURED PROJECTS" copy="Real digital products, platforms and experiments built for people—not just portfolios." /><div className="project-grid">{projects.map((p, i)=><article className={`project-card reveal ${i < 2 ? 'featured' : ''}`} key={p.name}><div className="project-preview"><img src={p.image} alt={`${p.name} website preview`} loading={i < 2 ? 'eager' : 'lazy'} /><div className="project-overlay"/><span>{p.code}</span><em>{t(p.type)}</em></div><div className="project-content"><div className="project-meta"><span>{t(p.category)}</span><i className={p.status === 'LIVE' ? 'live' : ''}>{p.status}</i></div><h3>{p.name}</h3><p>{t(p.description)}</p><div className="project-foot"><div className="tags">{p.tech.map(x=><span key={x}>{x}</span>)}</div>{p.url && <a href={p.url} target="_blank" rel="noreferrer" aria-label={`Visit ${p.name}`}><ArrowUpRight /></a>}</div></div></article>)}</div></section>
      <section id="lab" className="section lab-section"><SectionHeading t={t} index="04" eyebrow="PRODUCT SYSTEMS" title="ENGINEERING LAB" copy="The technical layers used to design, build, validate and deliver complete digital products." /><div className="lab-grid">{labs.map(l=><article className="lab-card reveal" key={l.id}><div><span>{l.id} / MODULE</span><i>● {l.status}</i></div><h3>{t(l.title)}</h3><p>{t(l.detail)}</p><div className="meter"><i /></div></article>)}</div><div className="lab-detail reveal"><div className="lab-title"><span>{t('ACTIVE CONFIGURATION')}</span><h3>{t('FULL STACK DELIVERY')}</h3><p>{t('A complete workflow connecting modern interfaces, typed services, persistent data and automated quality checks.')}</p></div><dl>{[['Frontend','React + TypeScript'],['Backend','Node.js + NestJS'],['Data','PostgreSQL'],['Quality','Playwright'],['CI/CD','GitHub Actions'],['Status','ACTIVE']].map(([a,b])=><div key={a}><dt>{t(a)}</dt><dd>{b}{a === 'Status' && <i />}</dd></div>)}</dl></div></section>
      <section id="cases" className="section"><SectionHeading t={t} index="05" eyebrow="QUALITY ENGINEERING" title="QA CAPABILITIES" copy="A practical overview of how I help teams prevent defects, automate confidence and deliver reliable, accessible software." /><div className="case-grid">{cases.map((c,i)=><article className="case-card reveal" key={c.title}><div className="case-top"><span>CAPABILITY.0{i+1}</span><b>{t('READY')}</b></div><h3>{t(c.title)}</h3><div className="case-type">{t(c.type)}</div><div className="case-narrative"><div><label>{t('WHAT I DO')}</label><p>{t(c.challenge)}</p></div><div><label>{t('HOW I WORK')}</label><p>{t(c.approach)}</p></div></div><label>{t('CORE COVERAGE')}</label><ul>{c.testing.map(x=><li key={x}><Check />{t(x)}</li>)}</ul><div className="case-result"><label>{t('VALUE TO THE TEAM')}</label><p>{t(c.outcome)}</p></div><div className="case-tools"><span>{t('TOOLS')}</span><b>{t(c.tools)}</b></div></article>)}</div>
        <div className="bug reveal"><div><span>BUG_ARCHIVE / 001</span><b>{t('FIXED')}</b></div><h3>{t('Keyboard interaction failure')}</h3><dl><div><dt>{t('CATEGORY')}</dt><dd>Accessibility</dd></div><div><dt>{t('SEVERITY')}</dt><dd>{t('Medium')}</dd></div><div><dt>{t('DETECTED')}</dt><dd>Manual Testing</dd></div><div><dt>{t('VALIDATED')}</dt><dd>Automated Regression</dd></div></dl></div>
      </section>
      <section id="stack" className="section"><SectionHeading t={t} index="06" eyebrow="SYSTEM CAPABILITIES" title="TECH STACK" copy="Tools used to build, verify and deliver digital products." /><div className="stack-grid">{Object.entries(stack).map(([group,items],i)=><article className="stack-card reveal" key={group}><span>0{i+1}</span><h3>{t(group)}</h3><div className="tags">{items.map(x=><b key={x}>{x}</b>)}</div></article>)}</div></section>
      <section id="opensource" className="section"><SectionHeading t={t} index="07" eyebrow="OPEN SOURCE / LABS" title="REPOSITORY FEED" /><div className="repo-list reveal">{repositories.map((r,i)=><a href="https://github.com/" target="_blank" rel="noreferrer" key={r[0]}><span>LAB.0{i+1}</span><div><h3>{r[0]}</h3><p>{t(r[1])}</p></div><b>{r[2]}</b><ArrowUpRight /></a>)}</div></section>
      <section id="contact" className="contact section"><div className="contact-status"><i/> {t('STATUS: AVAILABLE FOR OPPORTUNITIES')}</div><p>08 / {t('INITIATE CONNECTION')}</p><h2>{t("LET'S BUILD")}<br/><span>{t('RELIABLE SOFTWARE.')}</span></h2><div className="contact-actions"><a className="button primary" href="https://wa.me/573104555201" target="_blank" rel="noreferrer">{t('CONTACT ME')} <MessageCircle /></a><a aria-label="GitHub" href="https://github.com/" target="_blank" rel="noreferrer"><Code2 /></a><a aria-label="LinkedIn" href="https://www.linkedin.com/in/jdgiraldog01" target="_blank" rel="noreferrer"><Contact /></a><a aria-label="WhatsApp" href="https://wa.me/573104555201" target="_blank" rel="noreferrer"><MessageCircle /></a><a aria-label="Email" href="mailto:ingjdgiraldo@outlook.com"><Mail /></a></div><a className="contact-email" href="mailto:ingjdgiraldo@outlook.com">ingjdgiraldo@outlook.com</a></section>
    </main>
    <footer><a href="#home" className="logo">JD<span>_</span></a><p>JUAN DIEGO GIRALDO © 2026</p><span>{t('SYSTEM ONLINE')} · BOGOTÁ, CO</span></footer>
  </>
}
export default App
